org: lkorz
service: live055

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource: arn:aws:s3:::korzteste/*

package:
  individually: true

build:
  esbuild:
    minify: true
    bundle: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  upload:
    handler: src/main/functions/upload.handler
    events:
      - httpApi:
          path: /upload
          method: POST
  users:
    handler: src/main/functions/users.handler
    events:
      - httpApi:
          path: /users
          method: ANY
      - httpApi:
          path: /users/{param+}
          method: ANY
